language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  
env:
    - SYMFONY_VERSION=2.3.*
    - SYMFONY_VERSION=2.4.*
    - SYMFONY_VERSION=2.5.*
    - SYMFONY_VERSION=2.6.*
    - SYMFONY_VERSION=2.7.*
    - SYMFONY_VERSION=2.8.*
    - SYMFONY_VERSION=3.0.*
    - SYMFONY_VERSION=dev-master

before_script:
    - composer self-update
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
    - composer update --no-interaction --prefer-source
    - mkdir -p build/logs

script: 
    - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
    
after_success:
    - travis_retry php vendor/bin/coveralls -v
